package sample1.src.sample.Samplefileonly;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.List;
import java.util.stream.Collectors;

import javax.management.openmbean.OpenType;

public class GPTFileProcessor {

    private final String apiKey;

    public GPTFileProcessor(String apiKey) {
        this.apiKey = apiKey;
    }

    public boolean isGeneratedByGPT(File inputFile) throws Exception {
        // Read input file contents into a single string
        BufferedReader reader = new BufferedReader(new FileReader(inputFile));
        String inputText = reader.lines().collect(Collectors.joining());
        reader.close();

        // Send input text to OpenAI GPT API
        OpenType api = new OpenAI(apiKey);
        CompletionRequest request = new CompletionRequest.Builder()
                .prompt(inputText)
                .build();
        CompletionResponse response = ((Object) api).complete(request);

        // Extract generated text from API response
        List<String> choices = response.getChoices().stream().map(choice -> choice.getText())
                .collect(Collectors.toList());
        String generatedText = String.join(" ", choices);

        // Compare input and generated text to determine if the file was generated by
        // GPT
        double similarity = StringUtils.getJaccardSimilarity(inputText, generatedText);
        return similarity > 0.8; // Use a similarity threshold of 0.8
    }
}
